[project]
name = "genmail-server-retriever"
version = "0.1.0"
description = "Retriever part of genmail on server"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.129.0",
    "langchain==0.3.27",
    "uvicorn>=0.41.0",
]
