system:
  silent: True
  logging_file: null
  # LEVELS: 10 - DEB, 20 - INF, 30 - WARN, 40 - ERR, 50 - CRITERR
  logging_level: 20
  device: mps
  server: False


services:
  vectorbase:
    base_url: https://localhost:9200 # For server: localhost -> es01
    certs_path: ./data/certs/ca.crt
    indexes:
      message_history: message-history
      documents: docs-for-retriever
      document_info: doc-view
      chats: user-chats
      prompt_library: prompt-library
      context: saved-to-context
  
  graphbase:
    base_url: bolt://localhost:7687 # For server: localhost -> neo4j
  
  llm_engine:
    base_url: http://vllm_c:8000/v1 # For server: localhost -> vllm_c
  
  tablebase:
    base_url: localhost # For server: localhost -> postgres
  
  document_handler:
    base_url: http://localhost:${api.document_handler.port} # For server: localhost -> document_handler_c

  retriever:
    base_url: http://localhost:${api.retriever.port} # For server: localhost -> retriever_c

docs:
  main_dir: data/
  mail_dir_path: mails/
  final_name: result/result.docx


models:
  embeddings: FRIDA
  llm: "qwen3:8b"
  thinking_mode: True
  tools: True
  prompts_path: config/prompts/
  language: en # ru


api:
  main_back:
    port: ${oc.env:VITE_BACKEND_PORT}
    host: "0.0.0.0"
  
  document_handler:
    port: 8002
    host: "0.0.0.0"
  
  embeddings_model:
    port: 8003
    host: "0.0.0.0"
  
  retriever:
    port: 8004
    host: "0.0.0.0"


web:
  run_name: ${oc.env:VITE_CHAT_NAME}